apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: testx-app
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: basic-spring-boot
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: basic-spring-boot
  namespace: dsantra12
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: basic-spring-boot
status:
  configuration:
    generatedName: ""
